### ISSUE TITLE
Error when Accept header is 'application/json'

### ISSUE THREAD

**Issue by LordLyng** [itk-event-database/event-database-api#2]
I keep getting the same erro every time i try to set the Accept header to 'applciation/json' the error returned is shown below:
```json
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "detail": "No resource class found for object of type "AppBundle\Entity\Tag"."
}
```
The same is true for 'applciation/xml'

**Comment by rimi-itk** [comment]
Thanks for reporting this. I've fixed the issue.
