### ISSUE TITLE
Pagination for all getters.

### ISSUE THREAD

**Issue by LandSprutte** [itk-event-database/event-database-api#3]
Hi,

We are looking to make an app for this open API. Would you be so kind to implement some kind of pagination for the getters, loading in 30 occurrences / events is a bit too much in our case. 

:)

regards:
- Christian

**Comment by rimi-itk** [comment]
@ChristianBondesen It's already there: use `items_per_page` in the query, e.g.

```
https://api.detskeriaarhus.dk/api/events.jsonld?items_per_page=10
```

The Event API is based on [API Platform ](https://api-platform.com/) and we're using the built-in pagination (cf. https://api-platform.com/docs/core/pagination/#pagination).

Best regards,
Mikkel

**Comment by LandSprutte** [comment]
Did not know that was a thing! 

Thanks buddy :)
