### ISSUE TITLE
Documentation for occurrences

### ISSUE THREAD

**Issue by huulbaek** [itk-event-database/event-database-api#37]
What is an occurrence and what separates it from an event?

**Comment by rimi-itk** [comment]
@huulbaek, an _event_ has one or more occurrences and an _occurrence_ is when (and where) something, i.e, the event, takes place. Many events only occur once and thus only have one occurrence, but an event taking place every Monday in June 2023, say, will have 4 occurrences.

We're currently working on a new and improved Eventdatabase so we'll not improve on the current documentation (even though it could definitely use some improvements).

**Comment by huulbaek** [comment]
So, one last thing: What is the difference between an `Occurrence` and `DailyOccurrence`?

**Comment by rimi-itk** [comment]
If an occurrence spans multiple days, e.g. stars at 2001-01-01 12:00 and ends at 2001-01-03 10:00, that occurrence will be split into 3 daily occurrences:

1. 2001-01-01 12:00–2001-01-02 00:00
2. 2001-01-02 00:00–2001-01-03 00:00
3. 2001-01-03 00:00–2001-01-03 10:00

Daily occurrences never cross midnight and makes it easier to find and display occurrences in a calendar view (that shows days).

**Comment by huulbaek** [comment]
Gotcha, thx. :)
