### ISSUE TITLE
Past occurrences in event call

### ISSUE THREAD

**Issue by huulbaek** [itk-event-database/event-database-api#38]
This query seems to produce a lot of past occurrences. Am I using it wrong?

```
curl -X GET "https://api.detskeriaarhus.dk/api/events?occurrences.startDate%5Bbefore%5D=2023-11-19&occurrences.startDate%5Bafter%5D=2023-11-17&tags=For%20b%C3%B8rn" -H "accept: application/ld+json"
```

**Comment by rimi-itk** [comment]
Your query asks for _events_ having an _occurrence_ starting (on or) after 2023-11-17 and ending before (or on) 2023-11-19. An event can have many occurrences (cf. https://github.com/itk-event-database/event-database-api/issues/37#issuecomment-1816225127) and you get all occurrences on all events in the result.

If you only want to get occurrences, you should use the [`/api/occurrences`](https://api.detskeriaarhus.dk/api/docs#operations-Occurrence-getOccurrenceCollection) endpoint:

```shell
curl 'https://api.detskeriaarhus.dk/api/occurrences?startDate%5Bbefore%5D=2023-11-19&startDate%5Bafter%5D=2023-11-17'
```
