### ISSUE TITLE
Search for more than one tag

### ISSUE THREAD

**Issue by benjaminoerskov** [itk-event-database/event-database-api#4]
I have not found an option to search by more than one tag at a time. Is this possible? Or is it something you could implement?

**Comment by rimi-itk** [comment]
I've added a little info on how to filter by tags: https://github.com/itk-event-database/event-database-api/wiki/Filtering#filtering-events-by-tags.

Please see https://api.detskeriaarhus.dk/api/docs for details on what you can filter on.

Best regards,
Mikkel

**Comment by benjaminoerskov** [comment]
Thank you!

**Comment by benjaminoerskov** [comment]
Thank you!
Now im trying to put several parameters into the request, like so:
https://api.detskeriaarhus.dk/api/occurrences.jsonld?tags=Musik,Koncert&startDate[after]=now
This doesnt appear to work, since the tags are not correct (it works fine without the date parameter)... Is this a mistake in my url? Or does the server not handle multiple parameters, when working with jsonid? I assume its not because such occurrences simply doesnt exist, since it would then return an empty list..

**Comment by benjaminoerskov** [comment]
I've been working a little more with the API now. I can see that the filtering works as intended when working with events. Is it possible for you to add this filtering to occurrences as well?

**Comment by rimi-itk** [comment]
You can now filter occurrences by event tags, e.g. https://api.detskeriaarhus.dk/api/occurrences.jsonld?event.tags=Musik. Check out https://api.detskeriaarhus.dk/api/docs#!/Occurrence/getOccurrenceCollection for details.

Best regards,
Mikkel

**Comment by benjaminoerskov** [comment]
Sorry to bother you again. But I have now tried to use your new filtering on the occurrence API. However when I try to pass more than one parameter, I get a internal server error. See attached screenshot :)
![dsia api](https://user-images.githubusercontent.com/11537543/37584879-6b06aee6-2b57-11e8-8e84-0f0aa87caf21.PNG)

**Comment by rimi-itk** [comment]
No worries. I've tracked down – and fixed – a subtle bug in the tags filter. Now everything should work.

**Comment by benjaminoerskov** [comment]
Thank you! 
Another thing I noticed, is if I filter occurences by startDate[after]=now, I get occurrences after (and including) today.
However if I filter occurences by endDate[after]=now, I also get occurrences where endDate = null.. I dont think this is how its supposed to work.. :)

**Comment by rimi-itk** [comment]
In the Event database, an `endDate` of `null` means that an occurrences never ends, and therefore `endDate[after]=now` includes occurrences with no end date.

To get only occurrences with a non-null end date, you can add a condition on the end date being before some date in the far future, e.g.
```
https://api.detskeriaarhus.dk/api/occurrences.jsonld?endDate[after]=2019-05-01&endDate[before]=2100-01-01
```

By default, the Event database api only returns occurrences (and events) where the end date is after “now”.

**Comment by benjaminoerskov** [comment]
Alright, thanks alot!

**Comment by benjaminoerskov** [comment]
What does it mean when the startDate is null?

**Comment by rimi-itk** [comment]
It doesn't make sense. I've deleted the few occurrences having no start date.

**Comment by benjaminoerskov** [comment]
Cool, thanks a lot! Have a good weekend :)
