### ISSUE TITLE
feature-request: Organizers and Tags getByName

### ISSUE THREAD

**Issue by LandSprutte** [itk-event-database/event-database-api#5]
Hi,

Would be nice if you could fetch the tags and organizers by their name property.

Thanks and happy holidays :)

**Comment by rimi-itk** [comment]
A tag is basically a name, so it's not obvious (for me) what you mean by "fetch … tags … by their name property". Can you elaborate?

**Comment by LandSprutte** [comment]
I need an end-point for searching for tags and organizers by their name... basically
